### ISSUE TITLE
Redefinition of `gl_Position` causes crash on Galaxy S7

### ISSUE THREAD

**Issue by DiligentGraphics** [DiligentGraphics/DiligentCore#63]
Crash log:

```    
2019-02-22 11:38:07.253 9437-9454/com.diligentengine.tutorial03_texturing.Tutorial03Application A/Diligent Engine: Diligent Engine: CRITICAL ERROR in ShaderGLImpl() (ShaderGLImpl.cpp, 113): Failed to compile shader file "TexRegionRender : Vertex shader"
    InfoLog:
    0:42: L0006: Illegal identifier name 'gl_Position'
    0:42: S0022: Symbol 'gl_Position' redeclared
```

**Comment by DiligentGraphics** [comment]
@dolphineye I can't find any good explanation of when this is required. I had to add 'gl_Position' redeclaration because there was an a error on some other device.
The only universal method I can think of now is to try to create a test shader with 'gl_Position' and see if it compiles.

**Comment by DiligentGraphics** [comment]
@dolphineye The EXT_separate_shader_objects says the following:

```
When using GLSL ES 3.00 shaders in separable programs, gl_Position and 
    gl_PointSize built-in outputs must be redeclared according to Section 7.5 
    of the OpenGL Shading Language Specification. Other built-in inputs or 
    outputs do not affect interface matching. Any such built-in inputs are 
    well-defined unless they are derived from built-in outputs not written by 
    the previous shader stage."
    
    and add to GLSL ES 3.00 new section 7.5, Built-In Redeclaration and 
    Separable Programs:
    
    "The following vertex shader outputs may be redeclared at global scope to
    specify a built-in output interface, with or without special qualifiers:

        gl_Position
        gl_PointSize

      When compiling shaders using either of the above variables, both such
      variables must be redeclared prior to use.  ((Note:  This restriction
      applies only to shaders using version 300 that enable the
      EXT_separate_shader_objects extension; shaders not enabling the
      extension do not have this requirement.))  A separable program object
      will fail to link if any attached shader uses one of the above variables
      without redeclaration."
```
So I guess that means that redeclaring this for GLES3.0 only is proper solution

**Comment by dolphineye** [comment]
Again, we're in the non-spec-compliant Android devices field.

There's maybe a tricky option that we may explore. We could do basically like you did for the texture formats, and try to create some dummy shaders that try to redefine `gl_Position`. If the compilation fails because of that, we can set a variable that will disable the redefinition of `gl_Position` for that particular defective device.

I suppose that idea may be also relevant for https://github.com/DiligentGraphics/DiligentCore/issues/61.

What do you think?

**Comment by DiligentGraphics** [comment]
If my understanding of the spec is correct, it says that gl_Position must be redeclared in ES3.0 only, so ES3.1 should work fine. So I guess in this case the solution is legitimate. With shadow sampler precision qualifiers it seems like test shader could be the only solution.

**Comment by dolphineye** [comment]
For the test shaders (as for the texture formats tests), these are only performed on debug builds, right?

**Comment by dolphineye** [comment]
For `gl_Position`, the redeclaration failed on devices with GLES310+, so I guess putting some condition like `if (!IsES31OrAbove)` could do the job indeed.

**Comment by DiligentGraphics** [comment]
No, the tests are performed in all builds because that's the ultimate way to test if the format is supported. The textures are really small (8x8), so this should not be a performance issue

**Comment by DiligentGraphics** [comment]
The fix works fine on my GLES3.2 tablet.

**Comment by dolphineye** [comment]
Cool, thanks :)
